version: '3.8'

services:
  web:
    build: .
    container_name: django-app
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: on-failure

volumes:
  postgres_data: